bundles/basic_modes/lexers/python.lua, bundles/c/c_lexer.moon
- Reorder stuff in the C/C++ lexer to correctly lex things like `static_assert`.
- Remove Python decorator support. It disabled lexing for the rest of the line, which was ugly, and it was kind of broken.
=> Lexer fixes

bundles/basic_modes/lexers/python.lua, bundles/basic_modes/style_aliases.moon
@kirbyfan64 - Do you mind trying this out? This fixes the issue with the entire decorator line being unstyled. Instead, the '@' and just the following word is styled using the 'preproc' style.
=> Python decorator styling

lib/howl/buffer.moon, lib/howl/interactions/location_selection.moon, lib/howl/ui/editor.moon, lib/howl/ustring.moon, lib/howl/variables/core_variables.moon, spec/application_spec.moon, spec/buffer_spec.moon, spec/interactions/buffer_selection_spec.moon, spec/ui/editor_spec.moon, spec/ustring_spec.moon
- Don't reset last_shown on buffers during preview
- Add config.preview_files
- Don't preview binary files
Also, now the *-buffer-switch events are not fired during previewing.
=> Various file preview fixes

bundles/basic_modes/mode_definitions.moon, bundles/ruby/ruby_mode.moon, bundles/ruby/spec/ruby_mode_spec.moon
1. The Python lexer currently won't indent after `else:`.
2. Ruby function names can have the `!` and `?` characters.
=> More Python and Ruby lexer fixes

lib/howl/commands/app_commands.moon, lib/howl/keymap.moon, site/source/doc/manual/running_commands.md
This is a command I've had in my `init.moon` for a while now since it's quite handy, so I decided to send it in to see if you guys like it. This is *really* useful with projects written in compiled languages (e.g. C++, Crystal, etc.) and also works quite well with my [project extension](https://github.com/kirbyfan64/howl-proj).
=> Add build-exec

lib/howl/ui/editor.moon
Without this, for every other character I enter, I get an error message about indexing `nil` field `cur_style`.
=> Fix null error message

Changelog.md, lib/howl/interactions/line_selection.moon, lib/howl/interactions/location_selection.moon, lib/howl/interactions/selection_list.moon, site/source/doc/api/interact.md
The match highlighting worked only whenever a new line was selected, not if the match grew on the current line.
Also rename on_selection_change callback to on_change and trigger even when the user entered text changes.
=> Bugfix to highlight growing buffer-grep match

lib/howl/ui/searcher.moon
To reproduce the issue:
1. Open up a new file.
2. On the first line, type some text (I did `abc`).
3. Enter the same thing on the second line, but put a bunch of spaces before the text so that you need to scroll right to see it.
4. Move the cursor to the first line, first column.
5. Open a search for the text and go to the second match.
=> Fix not scrolling far enough to the right when searching for text

bundles/solarized-themes/light.moon, bundles/tomorrow-themes/tm_night_blue.moon, lib/aullar/buffer.moon, lib/aullar/config.moon, lib/aullar/current_line_marker.moon, lib/aullar/cursor.moon, lib/aullar/display_lines.moon, lib/aullar/flair.moon, lib/aullar/gutter.moon, lib/aullar/spec/buffer_spec.moon, lib/aullar/view.moon, lib/howl/ui/editor.moon, lib/ljglibs/cdefs/pango.moon, lib/ljglibs/pango/init.moon, lib/ljglibs/pango/layout.moon, spec/ui/cursor_spec.moon
This adds line wrapping support for aullar.  It supports the previously existing `line_wrapping` configuration variable, which supports wrapping on either character or word (or none). It also introduces two new configuration variables related to wrapping:
- `line_wrapping_navigation`
This provides control over how wrapped lines are navigated. "real" means cursor movement will step over the line in an ordinary fashion even if it's wrapped, and "visual" means that cursor movement will walk into a wrapped line. The mode is also reflected in the current line marker which will highlight the entire line for the former, and the visual line for the latter.
- `line_wrapping_symbol`
This is the symbol used for indicating wrapping at the right side of the wrapped visual line. The appearance of the …
=> Line wrapping

bundles/solarized-themes/light.moon, bundles/tomorrow-themes/tm_night_blue.moon, lib/aullar/buffer.moon, lib/aullar/flair.moon, lib/aullar/markers.moon, lib/aullar/spec/buffer_spec.moon, lib/aullar/spec/markers_spec.moon, lib/aullar/view.moon, lib/howl/buffer_markers.moon, lib/howl/interactions/line_selection.moon, lib/howl/ui/editor.moon, lib/howl/ui/highlight.moon, lib/howl/ui/list_widget.moon, lib/howl/ui/searcher.moon, spec/buffer_markers_spec.moon, spec/ui/highlight_spec.moon, spec/ui/list_widget_spec.moon
The twin to the previous optimization PR. This makes the adding of aullar markers, and in extension Howl highlights a multi-op affair, meaning we cut down on useless invalidations and refreshes.
Also included in this is changing the ListWidget to use highlights instead of styles for marking search hits (see commit message for a more elaborate discussion of the rationale).
=> Faster markers

lib/howl/bindings.moon, lib/howl/keymap.moon, lib/howl/sys.moon, spec/bindings_spec.moon, spec/sys_spec.moon
This adds support for OS specific bindings, by allowing for an optional `for_os` sub table in a key map. Included is a crude, incomplete and most likely incorrect set of base bindings for OS X.
=> Os bindings

lib/aullar/buffer.moon, lib/aullar/display_lines.moon, lib/aullar/spec/buffer_spec.moon, lib/aullar/view.moon, lib/howl/buffer.moon, lib/howl/ui/action_buffer.moon, lib/howl/ui/list_widget.moon, spec/buffer_spec.moon, spec/ui/action_buffer_spec.moon
This is a performance/efficiency improvement. The major theme is to extend the `change()` operation introduced a while ago. The original `change` collapsed buffer modifications notification into one single notification, with great results for larger operations such indenting large blocks of code.
This takes it further by also collecting and collapsing styling and marker changes, which makes it possible to optimize batch changes for text based interface buffers. This PR does just that for the ListWidget, where the write_page now writes everything in one change. 
Since I was primarily interested in reducing memory pressure I measured that, and the re-allocation of display lines is cut by approximately a third e.g. when interacting with `project-open`. From a performance perspective this …
=> More extensive change()

lib/howl/bindings.moon, lib/howl/signal.moon, lib/howl/ui/editor.moon, site/source/doc/api/signal.md, spec/bindings_spec.moon, spec/signal_spec.moon, spec/ui/editor_spec.moon
The `signal` module is one of the earliest modules written, and it was written from day one with an early-exit mechanism based on boolean values from signal handlers. This might have worked out fine if Lua had been used, but since we're using moonscript with its implicit returns it ended up a giant mistake, which makes it all to easy for signals to lost due to some implicit return somewhere.
The early-exit option is retained, but is now rather explicit due to the use of a required string return value instead.
=> Change early-exit behaviour in signal emission to be explicit

bundles/c/c_lexer.moon, bundles/c/misc/example.c
This should allow pretty much all C++ types to be properly highlighted.
=> Even *more* C/C++ lexer fixes

Changelog.md, lib/howl/buffer.moon, lib/howl/janitor.moon, lib/howl/sys.moon, lib/howl/ui/editor.moon, lib/ljglibs/cdefs/glib.moon, lib/ljglibs/glib/init.moon, site/source/doc/api/sys.md, spec/ui/editor_spec.moon
- uses g_get_real_time for microsecond resolution
- returns time as seconds (float) so comparable with os.time
Replaced use of os.time with sys.time
=> Added howl.sys.time for high resolution time

lib/howl/buffer.moon, lib/howl/interactions/buffer_selection.moon, spec/buffer_spec.moon, spec/interactions/buffer_selection_spec.moon, spec/project_spec.moon
- Removed title counters
- Default title is always basename
- Title unique-ification moved to switch-buffer command
- Unique-ification uses project name and parent directory name up to two levels
This also removes any counters and directory prefixes from the header bar of the editor - only the basename is displayed when viewing a file.
=> Rework buffer titles in `switch-buffer` list

lib/howl/interactions/buffer_selection.moon, lib/howl/ui/process_buffer.moon
Process buffer titles in the `switch-buffer` command can really blow up the width of the first column if the directory is deep. This moves the directory from the first 'title' column to the second column, also making it consistent with where the file buffer directories are shown.
=> Moved directory from process buffer title to directory column

Changelog.md, lib/howl/keymap.moon
- Changed `ctrl_w` to run `buffer-close` not `view-close`. Added `ctrl_shift_w` for `view-close`.
- Added `ctrl_[shift_](home|end)` bindings for moving cursor to start or end of buffer, optionally extending selection.
This fixes #112.
=> Keymap changes for #112

bundles/ruby/init.moon
Small change. Was looking for .jbuilder files to use ruby mode. Thought I'd add a few other common ones at the same time (inspired by the list in sublime).
=> Add some more extensions and filenames for ruby mode.

lib/howl/ui/editor.moon, spec/ui/editor_spec.moon
Similar to editor-duplicate-current and models the behaviour of a few other text editors - if you haven't a selection Ctrl+C/X will copy/cut the current line, instead of doing nothing. I find this very handy for moving a single line of code around.
=> Add editor-{copy,cut}-current to copy/cut the selection or otherwise current line

lib/howl/interactions/file_selection.moon
From tab completion in the shell, muscle memory always has me expecting tab in file selection to do something.
The idea I've implemented is to make it perform like bash/fish shell - if there is a unique entry, open that entry, otherwise cycle the selection through matched (non-new) entries. Feels pretty natural. Thoughts?
=> Add shell-like tab action on file selection.

lib/aullar/buffer.moon, lib/aullar/revisions.moon, lib/aullar/spec/revisions_spec.moon, lib/howl/buffer.moon, spec/buffer_spec.moon
The `buffer.modified` flag is now automatically reset to false if you undo all the way back to the originally synced revision. This avoids unnecessary 'Buffer is modified' warnings on close/exit and also the misleading '*' marker in the buffer list.
(I'm not quite sure if this is the best way to do this, but it works :smile: ).
=> Reset buffer 'modified' status after undo when applicable

lib/howl/interactions/buffer_selection.moon, spec/interactions/buffer_selection_spec.moon
This adds icons in the first column of the buffer list for `switch-buffer`. It also removes the status column which showed '*' for modified buffers since the icon indicates modification state. Custom icons also show status of process buffers - running, successful or error.
Some screenshots below (the icons should be self-explanatory, I hope):
=> Add icons to switch-buffer list

bundles/howl-themes/monokai/monokai.moon, bundles/howl-themes/solarized_light/solarized_light.moon, bundles/howl-themes/steinom/steinom.moon, bundles/howl-themes/tomorrow_night_blue/tm_night_blue.moon, lib/howl/ui/editor.moon
- prefer to match brace before cursor rather than after, when both
present
- highlight both braces of the matched pair
(`|` represents cursor, `^` represent hightlight)
When typing away, the last typed brace is matched in the common case. This is ideal because one usually wants to know which brace was just closed:
```
( ( ... ))|
^
```
However if you happen to be editing something and type a brace that happens to be just before another brace, the brace to the right of the cursor is matched:
```
( ( ... )|)
^  
```
This is confusing because it is inconsistent - one would still want to know (or expect to see) the brace that was just closed. To add to the confusion, there is no indication of which brace is being matched.
This PR always matching the brace *before* cursor, if present.
As a …
=> Change matching brace highlight behavior a bit

lib/howl/ui/editor.moon
This PR adjusts the behavior as per #150.
Using `backspace` to unindent now never moves the cursor to the right and always moves the cursor left. The conceptual idea is that the spaces to the left of the cursor are being deleted. Successive backspacing looks something like this:
```
|    abc
|    abc
|    abc
```
Using `shift_tab` to unindent now never moves the cursor to the right. It may move the cursor to the left to the first non blank character. The conceptual idea is that the rightmost spaces are being deleted. Successive shift-tabbing now looks something like this:
```
|    abc
|  abc
|abc
|abc
|abc
```
=> Change cursor behavior when unindenting line

lib/aullar/buffer.moon, lib/aullar/spec/buffer_spec.moon, lib/howl/commands/edit_commands.moon, lib/howl/ui/editor.moon, spec/ui/editor_spec.moon
- Made brace matching style aware, so operators are not matched with string literals, etc.
- Refactored brace matching implementation 
- Added cursor-match-brace command that moves cursor to matching brace, if any
=> Brace matching improvements

lib/howl/io/file.moon, spec/io/file_spec.moon
Currently, files like `x.c++` won't be highlighted with the C/C++ mode. When I looked into it, it turned out that the extension pattern wasn't matching `c++`, causing the correct mode to not be loaded. This fixes that by making sure that the pattern correctly matches any extension.
=> Fix matching of file extensions containing symbols

src/Makefile, src/tools/download
Tested under FreeBSD 10.2, of course, you should gmake instead make.
===
WoW, this is the first native modern editor for FreeBSD
=> Fix compilation under FreeBSD

bundles/howl-themes/blueberry_blend/blueberry_blend.moon, bundles/howl-themes/monokai/monokai.moon, bundles/howl-themes/steinom/steinom.moon, bundles/howl-themes/tomorrow_night_blue/tm_night_blue.moon, lib/howl/ui/theme.moon, lib/ljglibs/cdefs/gdk.moon, lib/ljglibs/gdk/rgba.moon, lib/ljglibs/spec/gdk/rgba_spec.moon
It didn't show itself to be much of a problem earlier, but probably only since the overlay scrollbars were often a visible orange, which wasn't that pleasing but at least clearly visible across all themes. When trying out Elementary OS however (for issue #200), whose theme uses black scrollbars, it's apparent that there is a problem if the scrollbars aren't visible.
So this makes scrollbars themeable. As ever, the Gtk support for CSS styling is a work of progress - I verified that this works on Ubuntu 16.04 and Elementary OS (Freya release, Gtk 3.14). I checked Ubuntu 14.04 and 12.04, where it's a no-op. I welcome any alternative choice for the actual colours choosen for the scrollbars of course.
Examples:
=> Make scrollbars themable

lib/howl/commands/edit_commands.moon
Replaces selection or buffer with output of external command fed the
selection or buffer.
=> Add editor-replace-exec command

lib/howl/ui/process_buffer.moon
This uses a highlight for the stderr and styles ANSI color codes
correctly.
Also added an opts.title parameter to the process buffer allowing a
custom title.
=> Allow process buffer to show color codes in stderr

Changelog.md, lib/aullar/markers.moon, lib/aullar/spec/markers_spec.moon, lib/howl/buffer_lines.moon, lib/howl/commands/edit_commands.moon, lib/howl/keymap.moon, lib/howl/ui/editor.moon, site/source/doc/api/ui/editor.md, spec/buffer_lines_spec.moon, spec/ui/editor_spec.moon
This adds the following commands:
* `editor-move-lines-up` - moves current or selected lines up by one line
* `editor-move-lines-down` - moves current or selected lines down by one line
See a preview here: https://www.youtube.com/watch?v=w9FPK4XtESo
This also contains the following API changes:
1. Adds a new API method `editor\with_selection_preserved` - this uses the markers to preserve the selection through buffer edits. 
2. Implements the trimming feature for markers that have `preserve: true` set - this causes markers to be trimmed rather than removed when text at either boundary is deleted.
=> Line motion commands and bindings

lib/howl/commands/edit_commands.moon, lib/howl/keymap.moon
Adds commands to move the selection (or current character) left and right by one character. Bound to `alt_right` and `alt_left`
=> Add editor-move-text-left|right commands

bundles/mail-mode/mail_lexer.moon, lib/howl/aux/lpeg_lexer.moon, spec/aux/lpeg_lexer_spec.moon
Where it previously internally used scan_until this is now left for the
user. This makes it possible to use arbitrary patterns for matching the
text to be sub lexed, e.g. `scan_through_indented`.
=> Generalize the sub_lex_by_inline lexer helper

bundles/vi/base_map.moon, bundles/vi/spec/vi_spec.moon
Same as `back_to_char` and `forward_to_char` except they stop one char before the match, like in vi.
Liking Howl so far, expect more vi mode pull requests from me. :)
=> Add {forward,back}_till_char keybinds to vi mode

lib/howl/ui/command_line.moon, lib/howl/ui/styled_text.moon, spec/ui/styled_text_spec.moon
Implements command line history persistence.
This saves the command line history and reloads it when Howl is started so pressing `up` after `alt_x` will show entries from the previous run. History is synced every time any command is run, so a crash or kill of the Howl process will leave the history saved as well. The saving mechanism attempts to merge new history with saved history so multiple running instances of Howl should not clobber each other's history, but instead produce a merged history.
This also implements full deduplication of history. Rerunning any historical command removes the old record and creates a new one.
=> Command history persistence

lib/howl/ui/completion_popup.moon, lib/howl/ui/editor.moon
Fixes #248 
Protects double invocation via an explicit `active` flag, rather than `showing`, which may not be immediately set on invocation.
=> Fix yielding completers

bin/howl-spec
The way to invoke this feature would be:
$ HOWL_SPEC_SINGLY=1 ./bin/howl-spec
$ HOWL_SPEC_SINGLY=1 ./bin/run-all-specs
Execution stops at first failure and return code is propagated back.
This will be useful to ensure that each spec also passes standalone and does not depend on the state left by another spec. This may also be useful to determine which spec is hanging since it prints the file name before execution.
On my machine, running `run-all-specs` with HOWL_SPEC_SINGLY enabled takes 28s, compared to 20s when run without.
=> Updated howl-spec to run each file standalone if desired.

lib/howl/modes/default_mode.moon, spec/modes/default_mode_spec.moon
Toggle comment with multiple selected lines only considered the first line
when deciding whether to comment or uncomment.  If the first line was
commented then it attempted to uncomment all lines - leaving already
uncommented lines unchanged.
=> Makes toggle-comment comment if any line not commented

bundles/moonscript/init.moon, bundles/moonscript/moonscript_inspector.moon, bundles/moonscript/moonscript_mode.moon, lib/aullar/display_lines.moon, lib/aullar/flair.moon, lib/aullar/markers.moon, lib/aullar/spec/markers_spec.moon, lib/ext/moonscript/moonscript/cmd/lint.lua, lib/howl/application.moon, lib/howl/buffer.moon, lib/howl/buffer_markers.moon, lib/howl/commands/app_commands.moon, lib/howl/commands/edit_commands.moon, lib/howl/config.moon, lib/howl/inspect.moon, lib/howl/inspection.moon, lib/howl/interactions/location_selection.moon, lib/howl/keymap.moon, lib/howl/timer.moon, lib/howl/ui/buffer_popup.moon, lib/howl/ui/command_line.moon, lib/howl/ui/editor.moon, lib/howl/ui/highlight.moon, lib/howl/variables/core_variables.moon, site/source/doc/api/buffer.md, spec/buffer_markers_spec.moon, spec/buffer_spec.moon, spec/inspect_spec.moon
This adds a first version of inspection support for Aullar. Inspectors are registered wit the `inspection` module, and the `inspect` module deals with running these according to configuration settings and displaying the results.
<hr/>
[previously] 
This is a work-in-progress branch for getting a generic inspections framework in place for Howl. It allows inspectors to be present for both buffers and their modes. All inspectors are run, with the results being coalesced and displayed visually for the buffer. As a first proof-of-concept a Moonscript inspector has been implemented (not coincidentally since that works for Howl code).
Current things to consider:
- Currently the inspections are run on save, but work is in progress to add inspections-on-idle as well.
- The inspectors are currently …
=> Buffer inspections

bundles/rust/init.moon, bundles/rust/rust_lexer.moon, bundles/rust/rust_mode.moon
First patch starting from 'initial commit' 1d8df75 to 754a618 in
[howl-rust].
These changesets introduce the [Rust] bundle into howl with full
lexical definition. The changesets continue feature request #224 and
also allow the progress of the bundle, with easier integration into
howl, from the [howl-rust] source.
[howl-rust]: https://bitbucket.org/a_baez/howl-rust
[Rust]: https://www.rust-lang.org/en-US/
=> Rust bundle patch introduction

lib/aullar/view.moon, lib/howl/ui/editor.moon
This PR does two things:
1. Currently, if a completion popup appears while the text is scrolled to the right, it will appear *outside* the Howl window. https://github.com/howl-editor/howl/commit/4b63690bbc12f7bcd603d5ff53e526ccb5247ff7 fixes that.
2. Even with that fixed, when the text scrolled, the popup would stay stationary. https://github.com/howl-editor/howl/commit/d0ea33bbdedc9a5886d1afc742bb0b8d688b3280 fixes that.
=> Popup fixes

lib/aullar/flair.moon, lib/ext/moonscript/README.md, lib/ext/moonscript/moonscript/cmd/args.lua, lib/ext/moonscript/moonscript/cmd/coverage.lua, lib/ext/moonscript/moonscript/cmd/lint.lua, lib/ext/moonscript/moonscript/cmd/moonc.lua, lib/ext/moonscript/moonscript/cmd/watchers.lua, lib/ext/moonscript/moonscript/compile/statement.lua, lib/ext/moonscript/moonscript/compile/value.lua, lib/ext/moonscript/moonscript/dump.lua, lib/ext/moonscript/moonscript/parse.lua, lib/ext/moonscript/moonscript/parse/literals.lua, lib/ext/moonscript/moonscript/parse/util.lua, lib/ext/moonscript/moonscript/transform/class.lua, lib/ext/moonscript/moonscript/transform/names.lua, lib/ext/moonscript/moonscript/transform/statement.lua, lib/ext/moonscript/moonscript/transform/value.lua, lib/ext/moonscript/moonscript/version.lua, lib/howl/commands/app_commands.moon, lib/howl/ui/process_buffer.moon
https://github.com/leafo/moonscript/releases/tag/v0.5.0
=> Update to Moonscript 0.5

lib/howl/command.moon, lib/howl/interactions/line_selection.moon, lib/howl/ui/list_widget.moon, lib/howl/ui/styled_text.moon, spec/ui/styled_text_spec.moon
The main motivation here is to make list selections more aesthetically pleasing.
1. Added following features to StyledTable, and consequently, to `interact.select` and related lists:
- Column `min_width`: Extra padding is added to make columns at least this wide. Specified as number of characters.
- Column `align: 'right'`: Cells are right aligned instead of left aligned.
2. Changed scrolling behavior of `ListWidget` to be row-wise instead of page-wise. This makes it look more like how buffers scroll when you hold down the `up` or `down` key. IOW, it scrolls in one line at a time, instead of jumping an entire page and re-positioning the selection at the top of that page.
3. Finally the above features have been activated in a couple of places:
- Added min_width for the command list …
=> ListWidget and StyledText enhancements

lib/howl/inspect.moon, lib/howl/io/process_output.moon, spec/inspect_spec.moon, spec/io/process_output_spec.moon
As part two of the new inspections framework introduced earlier comes this support for process based inspections. This makes it easy to just provide a command that should be run, with its output parsed for inspections.
Along with this comes a new module as well, `howl.io.process_output`, intended to provide one place for keeping the parsing smarts for parsing process output for various file references / messages.
=> Support process based inspections

bundles/ruby/init.moon, bundles/ruby/ruby_inspector.moon, bundles/ruby/ruby_mode.moon, bundles/ruby/spec/util_spec.moon, bundles/ruby/util.moon
This adds command-based inspection support for Ruby. It supports project-specific ruby versions (via `.ruby-version`) and RVM where detected.
=> Ruby inspection

lib/howl/buffer.moon, lib/howl/config.moon, lib/howl/mode.moon, site/source/doc/api/config.md, spec/buffer_spec.moon, spec/config_spec.moon
While buffer.config, mode.config and the set* commands can still be
used the same way, the underlying implementation has been changed.
The config is now organized along two dimensions - a primary dimension
called scope which is a hierarchial namespace, and a secondary
dimension called layer which can be any string. When defined, a layer
may be associated with another layer as the parent. For each scope,
multiple layers may exist and for each layer within the scope multiple
name/value pairs may exist.
Values are looked up in a scope, and if not found, the parent scopes
are checked, all the way from the immedidate parent to the global
scope, represented by the emtpy string ''. For each scope, value
resolution may check multiple layers.
Proxy config objects on buffer and mode hide most of …
=> Major config implementation refactor

lib/aullar/buffer.moon, lib/aullar/revisions.moon, lib/aullar/spec/revisions_spec.moon, lib/aullar/view.moon, lib/howl/ui/editor.moon
As noted in #156, we currently coalesce whenever we can. This is not the right thing to do as it will for instance mix pastes with ordinary inserts. With this PR we turn this around and never coalesce revisions unless the affected revisions are explicitly marked as supporting this. Fixes #156.
=> Only coalesce revisions when requested

lib/howl/application.moon, lib/howl/buffer.moon, lib/howl/commands/app_commands.moon, lib/howl/config.moon, lib/howl/mode.moon, spec/buffer_spec.moon, spec/config_spec.moon
Adds automatic configuration persistence. Fixes #13 
Config value set via command line or API can now be automatically persisted on clean exit. To enable this `config.save_config_on_exit` must be set to true (default is false). In addition, the `save-config` command can be used at any time to save the current config. The saved config is loaded automatically on the next startup.
Also includes a bugfix and replaces the `config.copy` method with `config.replace` and `config.merge` to make it more explicit.
=> Configuration auto persistence and more

src/Makefile
If Howl is running, the install won't complete the copy. I oftenly keep
several instances of Howl running for days (weeks) on end, and I might
not want to close down a certain session just to recompile. I think it's
the right thing (TM).
=> Add `force` to cp howl command in Makefile install

lib/howl/config.moon, spec/config_spec.moon
Config layer defaults should take precedence over global values.
=> Fix config evaluation for layer defaults

lib/howl/clipboard.moon, lib/howl/ui/editor.moon, lib/howl/ui/selection.moon, lib/ljglibs/cdefs/gtk.moon, lib/ljglibs/gtk/clipboard.moon, lib/ljglibs/gtk/init.moon, lib/ljglibs/gtk/selection_data.moon, lib/ljglibs/gtk/target_entry.moon, lib/ljglibs/gtk/target_list.moon, lib/ljglibs/gtk/target_table.moon, lib/ljglibs/spec/gtk/clipboard_spec.moon, site/source/doc/api/clipboard.md, spec/clipboard_spec.moon
This enables the use of the X11 primary selection from within Howl. It allows for pasting from the primary selection using the middle button, and also integrates the Howl selection with the primary selection in the system.
Fixes #308.
=> Primary selection

Changelog.md, lib/howl/buffer.moon, lib/howl/commands/app_commands.moon, lib/howl/config.moon, lib/howl/interact.moon, lib/howl/interactions/selection_list.moon, lib/howl/interactions/text_entry.moon, lib/howl/interactions/variable_assignment.moon, lib/howl/project.moon, lib/howl/ui/command_line.moon, site/source/doc/api/config.md, site/source/doc/manual/configuration.md, spec/config_spec.moon, spec/interact_spec.moon
The new set command has the following form:
```
set <name>@<scope>[<layer>]=<value>
```
The [<layer>] part is optional.
Examples:
```
set theme@global=Monokai
set indent@global[mode:moonscript]=2
set indent@project[mode:python]=4
set auto_inspect@buffer=manual
```
Selection lists provide auto-complete for the `name` and `scope` part,
making it generally unnecessary to type out the whole thing.
This is now implemented as a sequence of three interactions, rather
than one complex text entry interaction.
Backspacing backtracks to the previous interaction, allowing you to
edit any part of the command, but different than the current behavior
in that it clears the whole previous selection, rather than deleting
one character. (In that sense it is similar to backspacing into the
parent directory …
=> A new set command that unifies and replaces all existing set commands

lib/howl/bundle.moon, lib/howl/util/sandboxed_loader.moon, lint_config.moon, spec/bundle_spec.moon, spec/util/sandboxed_loader_spec.moon
Allow bundles to expose modules using `provide_module` helper
This allows for a bundle to easily vendor an entire lua module. The `provide_module` helper exposes this both internally within the bundle and externally with Howl, so that any files can be `require`d just as if they we're on the default search path.
=> Allow bundles to exposed vendored lua modules

bundles/moonscript/moonscript_mode.moon, bundles/ruby/ruby_mode.moon, lib/howl/inspect.moon, lib/howl/variables/core_variables.moon, spec/inspect_spec.moon
The previous solution had only one list of inspectors, and you could
chose when those would run (idle, save or manually). While this was a
simpler (and thus nicer in that sense) solution, it didn't allow for
running lightweight inspections on idle and heavy weight inspections
on save.
With this split there are now two configuration variables for
controlling what inspectors are run, `inspectors_on_idle` and
`inspectors_on_save`. The `auto_inspect` option now allows the
following three alternatives for controlling the running behaviour:
- manual: Run all inspectors when explicitly asked
- idle: Run on-idle inspectors on idle and on-save inspectors on save
- save: Run all inspectors, but only on save
@shalabhc How about this for your heavyweight stuff?
=> Allowing running different inspectors for idle and save

lib/howl/ui/editor.moon, spec/ui/editor_spec.moon
- Fixes #347
- Also don't set the config value unless different from existing value
=> Refresh editor config when buffer mode changes.

bundles/moonscript/init.moon, lib/howl/bundle.moon, lint_config.moon, spec/bundle_spec.moon
Adds a new bundle helper, `require_bundle`, that allows a bundle to declare itself as dependent on another bundle.
=> Add support for bundle dependency declarations

src/Makefile, src/tools/download
Hi folks. 
I try to build from source in the OpenBSD operatiing system, and need to make these two little changes.
This is basically the same rules for building on FreeBSD.
=> Changes to allow the build in the OpenBSD Operating System.

lib/howl/completer.moon, spec/completer_spec.moon
When a table is specified, the value of the 'completion' key is
inserted on accepting the completion. Tables are automatically
rendered as styled table and accept markup.
=> Allow completions to be tables in addition to strings

lib/howl/buffer.moon, lib/howl/buffer_lines.moon, spec/buffer_lines_spec.moon, spec/buffer_spec.moon
Automatically set EOL after loading a file, and fix buffer lines's .chunk to account for EOL according to @shalabhc's pointer.
Fixes #369
=> Better EOL handling

bundles/python/misc/examples.py, bundles/python/python_lexer.moon
The previous lexing was too loose. It would start a f string, scan until the
end or until a starting brace, and then lex anything followed by more f string
scanning. This obviously causes problems if the string has ended, but we still
lexed something else and continue with the f string.
Instead tighten up the lexing. We scan the f string until the end or until the
first brace. If and only if we're looking at an interpolation then attempt that,
but otherwise handle ends, etc., correctly.
Also lex double braces in f strings correctly.
Closes #379.
=> Improve Python lexing of f strings

lib/howl/bindings.moon, lib/ljglibs/util.moon, spec/bindings_spec.moon
While it's slightly weird, it makes it possible to use ordinary key
bindings (at least for the most common cases) even when typing with
caps lock on.
Fixes #282.
=> Switch binding translation character around when caps lock is on

Changelog.md, lib/howl/application.moon, lib/howl/breadcrumbs.moon, lib/howl/commands/app_commands.moon, lib/howl/commands/ui_commands.moon, lib/howl/keymap.moon, lib/howl/ui/cursor.moon, lib/howl/ui/searcher.moon, site/source/doc/api/breadcrumbs.md, site/source/doc/api/io/file.md, site/source/doc/index.haml, site/source/doc/manual/files.md, spec/breadcrumbs_spec.moon
This adds support for navigating back and forth in a list of previously visited locations (breadcrumbs). Two new commands, `navigate-back` and `navigate-forward` are added, bound to `ctrl_<` and `ctrl_>` respectively.
This allows one to quickly retrace one's step after switching buffers, or after jumping around in the current buffer via searches, buffer structure, etc.
=> Add support for navigation (breadcrumbs)

bundles/javascript/javascript_lexer.moon, bundles/javascript/misc/example.js
Prevents syntax highlighting from breaking when using ES6 template literals.
=> Basic support for ES6 template literals.

bundles/javascript/javascript_lexer.moon, bundles/javascript/misc/example.js
Hi.
Here's a refreshed list of js keywords with recent additions: `async`, `await`, `class`…
=> Add missing javascript keywords introduced in ES2015+

lib/aullar/config.moon, lib/aullar/view.moon, lib/howl/ui/editor.moon
Closes #415. Ping @italomaia, @tastyminerals. From my testing, this is virtually identical to Visual Studio Code's speed.
=> Increase the default scroll speed, and avoid over-scrolling

bundles/rust/misc/example.rs, bundles/rust/rust_lexer.moon
This series of commits adds an `example.rs` file and fixes the following in the Rust lexer:
- lifetime specifiers are given lower precedence than character literals
- `type` keyword is given lower precedence than `type` keyword
- rules for capturing numeric literals are re-implemented to better conform to Rust syntax rules
- support for Unicode character literals is added
Closes #442
=> Add an examples.rs file and fix a few bugs in the Rust lexer

lib/howl/commands/edit_commands.moon, spec/commands/edit_commands_spec.moon
Fixes #424, as well as another issue I found with `editor-move-text-right` at the second-to-last character.
=> Make sure editor-move-{lines-down},{text-right} work properly at EOF

lib/howl/buffer.moon, lib/howl/util/utf8.moon, lib/ljglibs/cdefs/glib.moon, spec/buffer_spec.moon, spec/util/utf8_spec.moon
There are a couple of reasons why this is always a good idea:
- Various routines in glib, etc., expects valid UTF-8. This is not a case of
it just being better in general either - I've seen the regex engine segfault
when attempting text-matching over invalid UTF-8 :(
- Our own offset caching does not behave exactly the same was a glib when
calculating the length of broken UTF-8. This cause mismatch errors when
doing boundary checks.
We use our own custom-written module for cleaning up UTF-8. There is also
a more performant variant available in glib, `g_utf8_make_valid`, but that
isn't available before glib 2.52 which was released only in 2017.
=> Ensure that buffers always contain valid UTF-8

lib/ljglibs/aux/background.moon, lib/ljglibs/cairo/context.moon
You can now set an alpha value for a background image. In addition, if you specify a color *and* an image, the color will be used as a background for the image, meaning that you can set an alpha value for the image and have it blended with the color.
=> Add some background image enhancements

lib/howl/application.moon, spec/application_spec.moon, spec/interactions/buffer_selection_spec.moon, spec/janitor_spec.moon
In short, when you have no buffers open, an Untitled empty buffer will be added. Then, when you proceed to open another file...the untitled buffer still stays open. This will now automatically close it.
=> Automatically remove an empty buffer when another one is added

lib/howl/sys.moon, src/io.howl.Editor.yaml
Basically, an app inside a Flatpak doesn't have full access to the host environment, meaning just trying to read `PATH` won't work.
This leaves out `lib/howl/interactions/external_command.moon`'s autocomplete capabilities, which I'm still trying to figure out how to cleanly fix...
=> Fix running external commands from Flatpak Howl

lib/howl/application.moon, lib/howl/commands/app_commands.moon, lib/howl/keymap.moon, lib/howl/log.moon, lib/howl/moonscript_support.lua, lib/howl/ui/journal_buffer.moon, lib/howl/ui/status.moon, spec/application_spec.moon, spec/interact_spec.moon, spec/log_spec.moon
This does two key things:
- It reworks logging to be based on signals and subscriptions. Anyone can now subscribe to log output. This can be handy for things like bundles to be able to listen to log events and send them to custom receivers (e.g. journald). Or, of course, it can be useful so we don't have to keep on making `log.dispatch` a huge function that sends events to a bunch of different places with a bunch of preconditions (a problem I ran into while adding the log buffer).
- Adds a log buffer that can be opened via `open-journal`. I named it the journal because *log* tends be used as a verb, which wouldn't fit with this noun-based usage.
I actually found two minor but interesting bugs in Howl while looking at the journal buffer, which I'll be fixing soon. :man_shrugging:
=> Rework logging to be signal-based and add a log buffer

site/source/getit.md, src/tools/download
Many distros now ship with curl but not wget out-of-the-box.
=> Support using curl to download

lib/howl/io/file.moon, site/source/doc/api/io/file.md, spec/io/file_spec.moon
`File.with_tmpfile()` now returns the return values of the passed callback, if successful, instead of an unhelpful `nil`.
=> Make File.with_tmpfile() return the callback result.

lib/howl/breadcrumbs.moon, lib/howl/config.moon, site/source/doc/api/config.md, spec/config_spec.moon
Renames the predefined config type `positive-number` to `positive_number`, following the snake case naming convention. Also documents and adds a spec for said type. Fixes #529.
=> Positive number snake case

bundles/rust/rust_lexer.moon
Been using for a bit now, ironically enough I ended up not using Rust for the project I added this for, but hey it's syntax highlighting improvements so ¯\\\_(ツ)\_/¯.
=> Rust syntax highlighting tweaks

site/source/doc/manual/configuration.md
Hello
This PR attempts to clarify that Howl also looks into `~/.config/howl/` dir for a startup file.
It should resolve the confusion in https://github.com/howl-editor/howl/issues/507
=> doc: mention $XDG_CONFIG_HOME in configuration - Fix #507

lib/howl/init.lua
Hi
`howl --version` currently displays this output: 
```
howl version 0.6-dev
Copyright 2012-2017 The Howl Developers
License: MIT License
```
This is a bit misleading because I first I thought that I had installed an old version but the `0.6` was published this year.
=> fix: update copyright year for --version flag

lib/howl/bindings.moon, lib/howl/log.moon, lib/howl/ui/editor.moon, lib/howl/ui/selection.moon, lib/howl/ui/theme.moon
Hello
With this PR, the `describe-signal` command output is now easier to visually scan.
Before:
After:
=> doc: homogenize signal descriptions

lib/howl/bindings.moon, lib/howl/ui/menu_popup.moon
Also add a list of modifiers to bindings.moon.
=> Don't close menu_popup when just a modifier key is pressed.

lib/howl/init.lua
Without this escaping the current directory pattern was not removed.
=> Fix path setup
