howl-editor/howl

Changelog.md
lib/howl/interactions/file_selection.moon
lib/howl/interactions/location_selection.moon
lib/howl/interactions/util/preview.moon
lib/howl/ui/editor.moon
lib/howl/ui/list_widget.moon

Adds preview functionality to `interact.select_file`

Implement preview for 'open' command

---

bundles/css/css_mode.moon
bundles/ruby/ruby_mode.moon
lib/howl/commands/app_commands.moon
lib/howl/commands/file_commands.moon
lib/howl/editing/text.moon
lib/howl/init.lua
lib/howl/ui/markup/terminal.moon
lib/howl/ui/theme.moon
lib/ljglibs/cdefs/glib.moon

Added check for the existance of a directory before
creating and auto_module table for an import.
Fixed various invalid imports.

Stricter auto_module loading

---

lib/howl/interactions/external_command.moon

The `up` key in 'exec' and 'project-exec' commands now pulls up previously run exec commands. History is not persisted across sessions yet.
@kirbyfan64 - did you get a chance to try this out?

Implemented history for exec and project-exec

---

Changelog.md
lib/howl/interactions/file_selection.moon
lib/howl/io/file.moon
lib/howl/util/paths.moon
lib/ljglibs/cdefs/glib.moon
lib/ljglibs/glib/init.moon
site/source/doc/manual/files.md
spec/interactions/file_selection_spec.moon
spec/util/paths_spec.moon

To try this out, press `ctrl_s` while running the open command to switch to subtree view. Press `ctrl_s` again to switch back.

Implement subtree mode for file interactions

---

.travis.yml

This should result in faster builds. For more info, see http://docs.travis-ci.com/user/workers/container-based-infrastructure/.

Try the new Travis container infrastructure

---

Changelog.md
lib/howl/commands/app_commands.moon
lib/howl/interactions/line_selection.moon
lib/howl/ui/command_line.moon
lib/howl/ui/list_widget.moon
site/source/doc/manual/editing.md
spec/interactions/line_selection_spec.moon
spec/ui/command_line_spec.moon

Here it is as discussed in #113. As a bonus, I've added `buffer-grep-exact`.

Added buffer-grep-exact and buffer-grep-regex commands

---

lib/howl/application.moon
lib/howl/commands/file_commands.moon
lib/howl/keymap.moon

I repushed my local 'open-recent' branch and looks like these are the leftovers that didn't get merged.

Open recent 2

---

Changelog.md
bundles/monokai-themes/README.md
bundles/monokai-themes/init.lua
bundles/monokai-themes/monokai.moon

Replacement PR for #165 based off master.

Monokai theme

---

lib/howl/interactions/buffer_selection.moon
spec/interactions/buffer_selection_spec.moon

I *was* going to just add another `if` branch, but then an alarm started going off in my head, considering that that would have resulted in *three* nested `if`s! Two is fine, but three felt like code smell to me.
Closes #179.

Rework buffer title code

---

lib/scripts/screen-shooter.moon

- buffer replace regex
- buffer modes
- commands (cheated a bit)
- configuration
- configuration help

Added a few more screenshots

---

lib/howl/application.moon

Previously those were just added to the list, which meant that they
ended up at the bottom of the buffer list. Now we make sure that we display
any new files, filling out any existing editors with the new files.
Previous loading didn't do any existing check either, we we really need to
when files are opened with the --reuse parameter.
Fixes #213.

Make sure we show any files opened with the --reuse parameter

---

lib/ext/serpent/LICENSE
lib/ext/serpent/README.md
lib/ext/serpent/init.lua

I renamed serpent.lua to init.lua so it can go in the folder.

Upgrade serpent to 0.28

---

lib/aullar/view.moon
lib/howl/ui/editor.moon

Fix drag select misbehaving for edge cases

---

lib/howl/commands/file_commands.moon

This fixes #220.
I don't have a spec for this, but this was really quick.

Update mode on 'save-as'

---

lib/aullar/view.moon
lib/howl/ui/editor.moon
lib/howl/ui/selection.moon
spec/ui/selection_spec.moon

Don't scroll to bottom on select all

---

bundles/moonscript/moonscript_inspector.moon
lib/ext/moonpick/config.lua
lib/ext/moonpick/init.lua
lib/howl/init.lua

Written by yours truly, moonpick is a new Moonscript linter that detects
more potential issues with Moonscript code:
https://github.com/nilnor/moonpick

Moonscript: Switch to the new moonpick linter instead of the built-in

---

bundles/hg/hg.moon
bundles/hg/init.moon
bundles/hg/spec/hg_spec.moon

Copied and adapted from bundles/git.

bundles/hg: add support for Mercurial SCM (aka "hg").

---

lib/howl/bindings.moon

This makes the keypad work as intended on my Fedora machine.

bindings: better support for keypad keys.

---

share/appdata/howl.appdata.xml

for Linux software gallery integration.
See https://people.freedesktop.org/~hughsient/temp/AppData_WhitePaper.pdf for details.

Added an AppData compatible metadata file

---

Changelog.md
lib/aullar/config.moon
lib/howl/ui/editor.moon

If there are no objections. Fix #326.

Change default for line-padding to 0

---

lib/howl/ui/editor.moon
spec/ui/editor_spec.moon

Fixes #344 
(Second attempt at fixing this - this time the code is much smarter about not updating stuff unnecessarily)

Fix config broadcast handling for editors

---

site/source/index.haml

This description had the wrong year

Corrected 0.5 release date on site

---

lib/howl/init.lua

https://github.com/howl-editor/howl/issues/349#issuecomment-312930234

Update init.lua for Howl 0.5.0

---

lib/aullar/config.moon
lib/aullar/view.moon
lib/howl/ui/editor.moon

Just installed Arch Linux, only to discover my precious two-finger scrolling wasn't working...turns out, Gtk+ and Wayland mixed don't support two-finger scrolling without smooth scrolling.

Smooth scrolling support

---

lib/howl/commands/app_commands.moon

Use the buffer config in project-build

---

lib/aullar/view.moon

This should fix the bug @rokf ran into. I'm seriously surprised this never came up before, considering how stupid the mistake was...

Fix a nasty smooth scrolling bug

---

bundles/howl-themes/README.md
bundles/howl-themes/dracula/dracula.moon
bundles/howl-themes/init.moon

Hi
This PR introduces a dracula theme https://draculatheme.com/
https://github.com/dracula/dracula-theme
It's mainly a transposition of the monokai one, so it may need some refinements in future PRs.

Add dracula theme

---

lib/howl/io/file.moon
spec/interactions/file_selection_spec.moon
spec/io/file_spec.moon

Fix File.expand_path to handle ~ within names

---

.gitignore
site/source/doc/api/bindings.md
site/source/doc/api/ui/editor.md
site/source/doc/manual/configuration.md

Fixed some typos in `bindings.md` and `editor.md`.
Added `site/.bundle` to gitignore, because my Bundler is
configured to download and build gem dependenies per project.

Added warning about requiring howl module in configuration manual.

---

lib/howl/ui/window.moon
lib/ljglibs/cdefs/gtk.moon
lib/ljglibs/gtk/init.moon

Allow disabling titlebar hiding when maximized

---

lib/howl/ui/process_buffer.moon

Fix resolve_location regex in process_buffer.moon for Maven builds

---

lib/howl/application.moon
lib/ljglibs/cdefs/gio.moon
lib/ljglibs/gio/application_command_line.moon

Fix for --reuse with relative file paths

---

.travis.yml

Travis builds are failing. This fixes them: https://travis-ci.org/howl-editor/howl/builds/574188809

Fix travis xvfb setup

---

lib/howl/ui/searcher.moon

Fix for buffer search matches being obscured

---

site/source/doc/manual/files.md

Just a couple mistakes I noticed while reading the docs.

doc: fix one typo and one incorrectly docummented default binding

---

lib/howl/application.moon
lib/howl/ui/editor.moon

Fixes https://github.com/howl-editor/howl/issues/561

Fix for jumping to a location in the current file from cmd line

---

lib/howl/commands/app_commands.moon
lib/howl/file_search.moon

An attempt to provide the functionality discussed in #558.

Folder search

---

lib/howl/buffer.moon
lib/howl/explorers/buffer_explorer.moon
lib/howl/ui/buffer_icon.moon
lib/howl/ui/editor.moon

Implements feature request #589

Add status indicators in the title bar for buffers.

---

README.md

I was stucked on the compilation because my recently installed Archlinux didn't include pkg-config.

Little update on README.md

---

share/metainfo/howl.appdata.xml

- Fix missing developer name and other issues.

appdata: patch appdata
